# Generated by Django 6.0.4 on 2026-04-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('event_date', models.DateField(blank=True, null=True, verbose_name='Дата мероприятия')),
                ('message', models.TextField(blank=True, verbose_name='Комментарий клиента')),
                ('guests', models.PositiveIntegerField(blank=True, null=True, verbose_name='Гостей')),
                ('calc_data', models.JSONField(blank=True, help_text='JSON с настройками калькулятора', null=True, verbose_name='Параметры расчета')),
                ('total_sum', models.PositiveIntegerField(blank=True, null=True, verbose_name='Сумма из расчета')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('work', 'В работе'), ('done', 'Закрыта'), ('cancel', 'Отмена')], default='new', max_length=20, verbose_name='Статус')),
                ('manager_note', models.TextField(blank=True, verbose_name='Заметка менеджера')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
