# Generated by Django 6.0.4 on 2026-04-10 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(help_text='Например: home, contacts', unique=True, verbose_name='URL-адрес')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок блока')),
                ('content', models.TextField(blank=True, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blocks/', verbose_name='Изображение')),
                ('block_type', models.CharField(choices=[('text', 'Текст'), ('image', 'Изображение'), ('hero', 'Главный экран'), ('cta', 'Призыв к действию')], max_length=50, verbose_name='Тип')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='core.page', verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'Блок контента',
                'verbose_name_plural': 'Блоки контента',
                'ordering': ['order'],
            },
        ),
    ]
