# Generated by Django 6.0.4 on 2026-04-10 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название мероприятия')),
                ('date', models.DateField(verbose_name='Дата')),
                ('guests_count', models.PositiveIntegerField(verbose_name='Гостей')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Место')),
                ('description', models.TextField(verbose_name='Описание')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Кейс',
                'verbose_name_plural': 'Кейсы',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('logo', models.ImageField(upload_to='clients/', verbose_name='Логотип')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='CaseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cases/', verbose_name='Фото')),
                ('is_cover', models.BooleanField(default=False, verbose_name='Обложка')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gallery.case')),
            ],
            options={
                'verbose_name': 'Фото кейса',
                'verbose_name_plural': 'Фото кейсов',
            },
        ),
    ]
