"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.3.
Optimized for Railway.com deployment.
"""

import os
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url  # Для парсинга DATABASE_URL от Railway

# load_dotenv() читает .env при локальной разработке.
# override=False гарантирует, что системные переменные окружения (Railway)
# НИКОГДА не перезаписываются значениями из .env файла.
load_dotenv(override=False)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# os.environ.get() читает системные переменные окружения напрямую —
# именно так Railway передаёт все переменные сервиса.
SECRET_KEY = os.environ.get('SECRET_KEY')

# Диагностика при старте: видно в логах Railway Deploy
print(f"🔑 SECRET_KEY {'установлен ✅' if SECRET_KEY else 'НЕ НАЙДЕН ❌'}")
print(f"🌍 Все переменные окружения: {[k for k in os.environ if not k.startswith('_')]}")

if not SECRET_KEY:
    if os.environ.get('DEBUG', 'False').lower() in ('true', '1', 'yes'):
        SECRET_KEY = 'dev-secret-key-CHANGE-ME-in-production'
        print("⚠️  WARNING: Using default SECRET_KEY for development!")
    else:
        raise ValueError(
            "❌ SECRET_KEY не задан! Убедитесь, что переменная SECRET_KEY "
            "добавлена в Variables сервиса на Railway."
        )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() in ('true', '1', 'yes')

# ALLOWED_HOSTS: локально + все поддомены Railway
# filter(None, ...) убирает пустые строки, которые возникают при split('')
_allowed_hosts_env = os.environ.get('ALLOWED_HOSTS', '')
ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_env.split(',') if h.strip()]
if not ALLOWED_HOSTS:
    ALLOWED_HOSTS = [
        'localhost', '127.0.0.1', '[::1]',      # Локальная разработка
        '.railway.app', '.up.railway.app'       # Автоматические домены Railway
    ]


# Application definition
INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Сторонние
    'import_export',
    'ckeditor',
    'ckeditor_uploader',

    # Наши приложения
    'utils',
    'core',
    'catalog',
    'gallery',
    'calculator',
    'leads',
]

CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Custom',
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline'],
            ['NumberedList', 'BulletedList'],
            ['Link', 'Unlink'],
            ['RemoveFormat'],
        ],
        'removePlugins': 'iframe,forms,flash,div',
        'height': 300,
    },
}

JAZZMIN_SETTINGS = {
    "site_title": "Личный кабинет BarPro",
    "site_header": "Управление сайтом",
    "site_brand": "BarPro Admin",
    "welcome_sign": "Добро пожаловать в панель управления",
    "copyright": "BarPro Ltd",
    "search_model": ["leads.Lead", "catalog.Cocktail"],
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # ✅ Whitenoise для статики на Railway
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
# ✅ Railway автоматически создает переменную DATABASE_URL для PostgreSQL
if os.environ.get('DATABASE_URL'):
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get('DATABASE_URL'),
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    # SQLite для локальной разработки
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/
LANGUAGE_CODE = 'ru'
TIME_ZONE = 'Europe/Moscow'
USE_I18N = True
USE_TZ = True
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

# ✅ Настройка Whitenoise для сжатия и кэширования статики в продакшене
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Ограничение размера загружаемых файлов
DATA_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024


# Security settings for production
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True


# Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {'format': '{levelname} {asctime} {module} {message}', 'style': '{'},
        'simple': {'format': '{levelname} {message}', 'style': '{'},
    },
    'handlers': {
        'file': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'maxBytes': 1024 * 1024 * 10,
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {'handlers': ['file', 'console'], 'level': 'WARNING', 'propagate': True},
        'leads': {'handlers': ['file', 'console'], 'level': 'INFO', 'propagate': False},
        'calculator': {'handlers': ['file', 'console'], 'level': 'INFO', 'propagate': False},
    },
}