# Generated by Django 6.0.4 on 2026-04-10 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddonService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Услуга')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text="Оставьте пустым, если 'По запросу'", max_digits=10, null=True, verbose_name='Цена (₽)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Иконка (класс CSS или эмодзи)')),
                ('is_active_in_calc', models.BooleanField(default=True, verbose_name='Доступно в калькуляторе')),
            ],
            options={
                'verbose_name': 'Доп. услуга',
                'verbose_name_plural': 'Доп. услуги',
            },
        ),
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('composition', models.TextField(help_text='Перечислите ингредиенты', verbose_name='Состав')),
                ('strength', models.CharField(blank=True, max_length=50, verbose_name='Крепость')),
                ('price', models.DecimalField(decimal_places=2, help_text='Используется для расчета в пакете', max_digits=10, verbose_name='Цена за коктейль (₽)')),
                ('type', models.CharField(choices=[('alco', 'Алкогольный'), ('non_alco', 'Безалкогольный')], max_length=20, verbose_name='Тип')),
                ('image', models.ImageField(blank=True, upload_to='menu/', verbose_name='Фото')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Коктейль',
                'verbose_name_plural': 'Коктейли',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название пакета')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Базовая цена пакета (₽)')),
                ('image', models.ImageField(upload_to='packages/', verbose_name='Обложка')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Хит продаж')),
            ],
            options={
                'verbose_name': 'Пакет',
                'verbose_name_plural': 'Пакеты',
            },
        ),
        migrations.CreateModel(
            name='PackageCocktail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portions', models.PositiveIntegerField(verbose_name='Кол-во порций')),
                ('cocktail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.cocktail')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.package')),
            ],
            options={
                'verbose_name': 'Состав пакета',
                'verbose_name_plural': 'Состав пакетов',
            },
        ),
        migrations.AddField(
            model_name='package',
            name='cocktails',
            field=models.ManyToManyField(through='catalog.PackageCocktail', to='catalog.cocktail', verbose_name='Коктейли в пакете'),
        ),
    ]
