# Generated by Django 5.1.3 on 2026-04-21 17:15

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_premium_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemedBarProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Тематический бар',
                'verbose_name_plural': '🍹 Тематические бары',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.addonservice',),
        ),
        migrations.RemoveField(
            model_name='addonservice',
            name='icon',
        ),
        migrations.AddField(
            model_name='addonservice',
            name='image',
            field=models.ImageField(blank=True, help_text='Рекомендуемый размер: 800×600 px. Форматы: JPG, PNG, WEBP', null=True, upload_to='addons/', verbose_name='Фото услуги'),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='image',
            field=models.ImageField(blank=True, help_text='Максимальный размер: 5 МБ. Форматы: JPG, PNG, GIF, WEBP', upload_to='menu/', validators=[utils.validators.validate_image_file], verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='package',
            name='image',
            field=models.ImageField(help_text='Максимальный размер: 5 МБ. Форматы: JPG, PNG, GIF, WEBP', upload_to='packages/', validators=[utils.validators.validate_image_file], verbose_name='Обложка'),
        ),
    ]
