# Generated by Django 6.0.4 on 2026-04-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatorSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bartender_price', models.PositiveIntegerField(default=3000, verbose_name='Цена часа бармена (₽)')),
                ('cocktail_base_price', models.PositiveIntegerField(default=450, verbose_name='Средняя цена коктейля (₽)')),
                ('min_guests', models.PositiveIntegerField(default=10, verbose_name='Мин. гостей')),
                ('max_guests', models.PositiveIntegerField(default=500, verbose_name='Макс. гостей')),
            ],
            options={
                'verbose_name': 'Настройки калькулятора',
            },
        ),
    ]
